[Ivy]
[>Created: Wed Feb 15 09:50:44 CET 2017]
15A3C61329EEE807 3.20 #module
>Proto >Proto Collection #zClass
Ca0 CreateTestData Big #zClass
Ca0 B #cInfo
Ca0 #process
Ca0 @TextInP .resExport .resExport #zField
Ca0 @TextInP .type .type #zField
Ca0 @TextInP .processKind .processKind #zField
Ca0 @AnnotationInP-0n ai ai #zField
Ca0 @MessageFlowInP-0n messageIn messageIn #zField
Ca0 @MessageFlowOutP-0n messageOut messageOut #zField
Ca0 @TextInP .xml .xml #zField
Ca0 @TextInP .responsibility .responsibility #zField
Ca0 @StartRequest f0 '' #zField
Ca0 @EndTask f1 '' #zField
Ca0 @GridStep f3 '' #zField
Ca0 @PushWFArc f4 '' #zField
Ca0 @InfoButton f7 '' #zField
Ca0 @InfoButton f5 '' #zField
Ca0 @GridStep f6 '' #zField
Ca0 @PushWFArc f8 '' #zField
Ca0 @PushWFArc f2 '' #zField
Ca0 @InfoButton f9 '' #zField
Ca0 @InfoButton f10 '' #zField
Ca0 @InfoButton f11 '' #zField
Ca0 @InfoButton f12 '' #zField
Ca0 @InfoButton f13 '' #zField
Ca0 @InfoButton f14 '' #zField
>Proto Ca0 Ca0 CreateTestData #zField
Ca0 f0 outLink start.ivp #txt
Ca0 f0 type com.axonivy.sample.hibernateenvers.Data #txt
Ca0 f0 inParamDecl '<> param;' #txt
Ca0 f0 actionDecl 'com.axonivy.sample.hibernateenvers.Data out;
' #txt
Ca0 f0 guid 15A3C613371C0382 #txt
Ca0 f0 requestEnabled true #txt
Ca0 f0 triggerEnabled false #txt
Ca0 f0 callSignature start() #txt
Ca0 f0 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>start.ivp</name>
    </language>
</elementInfo>
' #txt
Ca0 f0 @C|.responsibility Everybody #txt
Ca0 f0 49 81 30 30 -21 17 #rect
Ca0 f0 @|StartRequestIcon #fIcon
Ca0 f1 type com.axonivy.sample.hibernateenvers.Data #txt
Ca0 f1 561 81 30 30 0 15 #rect
Ca0 f1 @|EndIcon #fIcon
Ca0 f3 actionDecl 'com.axonivy.sample.hibernateenvers.Data out;
' #txt
Ca0 f3 actionTable 'out=in;
' #txt
Ca0 f3 actionCode 'import com.axonivy.samples.hibernateenvers.entities.CreditCard;

CreditCard cc = new CreditCard();
cc.nameOnCard = "Hans Muster";
cc.creditcardType = "VISA";
cc.creditcardValidMonth = 9;
cc.creditcardValidYear = 2029;
cc.creditcardNumberLast4Digits = "3254";
cc.isActive = true;

ivy.persistence.DefaultInMemoryDB.persist(cc);

in.creditcardIdInDb = cc.id;
' #txt
Ca0 f3 type com.axonivy.sample.hibernateenvers.Data #txt
Ca0 f3 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>Create CreditCard</name>
        <nameStyle>17,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f3 120 72 176 48 -50 -8 #rect
Ca0 f3 @|StepIcon #fIcon
Ca0 f4 expr out #txt
Ca0 f4 79 96 120 96 #arcP
Ca0 f7 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>2. Manually create Revinfo Table (with Definitions/Databases/ Execute SQL):

    create table REVINFO (
        REV integer generated by default as identity (start with 1),
        REVTSTMP bigint,
        primary key (REV)
    );</name>
        <nameStyle>76,7
154,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f7 88 242 432 124 -207 -56 #rect
Ca0 f7 @|IBIcon #fIcon
Ca0 f5 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>3. Manually create CreditCard_AUD Table (with Definitions/Databases/ Execute SQL):

    create table CreditCard_AUD (
        id integer not null,
        creditcardNumberLast4Digits varchar(4),
        creditcardType varchar(30),
        creditcardValidMonth integer,
        creditcardValidYear integer,
        isActive boolean,
        nameOnCard varchar(200),
        REV integer not null,
        REVTYPE tinyint,
        primary key (id, REV)
    )</name>
        <nameStyle>455,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f5 88 410 480 236 -232 -112 #rect
Ca0 f5 @|IBIcon #fIcon
Ca0 f6 actionDecl 'com.axonivy.sample.hibernateenvers.Data out;
' #txt
Ca0 f6 actionTable 'out=in;
' #txt
Ca0 f6 actionCode 'import com.axonivy.samples.hibernateenvers.entities.CreditCard;

CreditCard cc = ivy.persistence.DefaultInMemoryDB.find(CreditCard.class,in.creditcardIdInDb) as CreditCard;
cc.nameOnCard = "Julia Sample";
cc.creditcardType = "American Express";

ivy.persistence.DefaultInMemoryDB.merge(cc);' #txt
Ca0 f6 type com.axonivy.sample.hibernateenvers.Data #txt
Ca0 f6 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>Modify CreditCard</name>
        <nameStyle>17,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f6 348 72 168 48 -48 -8 #rect
Ca0 f6 @|StepIcon #fIcon
Ca0 f8 expr out #txt
Ca0 f8 296 96 348 96 #arcP
Ca0 f2 expr out #txt
Ca0 f2 516 96 561 96 #arcP
Ca0 f9 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>1. Create CreditCard Table: Go To Persisence, Select PU, And Execute ''Generate Schema''</name>
        <nameStyle>86,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f9 88 177 496 30 -245 -8 #rect
Ca0 f9 @|IBIcon #fIcon
Ca0 f10 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>4. Execute Process</name>
        <nameStyle>18,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f10 88 681 112 30 -52 -8 #rect
Ca0 f10 @|IBIcon #fIcon
Ca0 f11 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>5. On the in-memory-db: ''Select * From CreditCard_AUD'' and see how the change values are stored.</name>
        <nameStyle>96,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f11 88 753 560 30 -273 -8 #rect
Ca0 f11 @|IBIcon #fIcon
Ca0 f12 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>If needed: this is how the CreditCard Table can be created:

    create table CreditCard (
        id integer generated by default as identity (start with 1),
        creditcardNumberLast4Digits varchar(4),
        creditcardType varchar(30),
        creditcardValidMonth integer,
        creditcardValidYear integer,
        isActive boolean,
        nameOnCard varchar(200),
        primary key (id)
    )</name>
        <nameStyle>60,7
347,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f12 96 1138 336 204 -160 -96 #rect
Ca0 f12 @|IBIcon #fIcon
Ca0 f13 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>For MySQL use this for ids:
id integer NOT NULL AUTO_INCREMENT</name>
        <nameStyle>62,7
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f13 96 1386 240 44 -113 -16 #rect
Ca0 f13 @|IBIcon #fIcon
Ca0 f14 @C|.xml '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<elementInfo>
    <language>
        <name>This is an ivy Project sample that shows how Hibernate Envers can be used with ivy.
It should not be used as Hibernate sample.</name>
        <nameStyle>126
</nameStyle>
    </language>
</elementInfo>
' #txt
Ca0 f14 88 10 496 44 -242 -15 #rect
Ca0 f14 @|IBIcon #fIcon
>Proto Ca0 .type com.axonivy.sample.hibernateenvers.Data #txt
>Proto Ca0 .processKind NORMAL #txt
>Proto Ca0 0 0 32 24 18 0 #rect
>Proto Ca0 @|BIcon #fIcon
Ca0 f0 mainOut f4 tail #connect
Ca0 f4 head f3 mainIn #connect
Ca0 f3 mainOut f8 tail #connect
Ca0 f8 head f6 mainIn #connect
Ca0 f6 mainOut f2 tail #connect
Ca0 f2 head f1 mainIn #connect
